### ISSUE TITLE
Regression on Haiku

### ISSUE THREAD

**Issue by iam-git** [pyqtgraph/pyqtgraph#1976]
Not sure, what's going on, but 0.12.x versions look weird on Haiku (screenshots are made for python 3.8, PyQt5 5.15.2):
pg 0.12.x: http://0x0.st/-tup.png
pg 0.11.1: http://0x0.st/-tu9.png

![-tup](https://user-images.githubusercontent.com/23620506/131231088-4e83299d-38a7-496c-b0d0-d620acb0eb8f.png)
![-tu9](https://user-images.githubusercontent.com/23620506/131231090-dd9585f7-dba0-4d16-8ae5-e1bfe134833f.png)

**Comment by pijyoi** [comment]
Would you mind trying out the following:
Find the following lines in ```pyqtgraph/Qt/__init__.py``` and replace them with a ```pass``` statement
```python
os.environ["QT_ENABLE_HIGHDPI_SCALING"] = "1"
QtGui.QApplication.setHighDpiScaleFactorRoundingPolicy(QtCore.Qt.HighDpiScaleFactorRoundingPolicy.PassThrough)
```

**Comment by iam-git** [comment]
yes, it solves the issue!

**Comment by iam-git** [comment]
it appears, the latest matplotlib has similar issue. Probably it should be solved on different level. 
Thank you!

**Comment by pijyoi** [comment]
I had encountered something similar on a Linux system running Mate Desktop. It turns out that the issue had to do with a non-standard dpi setting configured on the desktop. Resetting that dpi setting fixed the issue. Perhaps it's a similar issue with your system? 

My suggestion to you just now was to see if it was dpi related. Wasn't to indicate that the pyqtgraph code was faulty.

**Comment by ntjess** [comment]
@iam-git do you mind if I edit your post to add the images directly as attachments? Since the link you shared indicates the images expire, it would be good for them to stay in the post history even after 0x0 stops hosting them.

**Comment by j9ac9k** [comment]
I'm going to close out this issue as I'm not sure what we can do in the code-base to make this better for users.  We're dependent on Qt and the OS doing proper hidpi handling, which is still not as robust as it should be :(
