### ISSUE TITLE
Transparent NaN pixels in ImageItem

### ISSUE THREAD

**Issue by miili** [pyqtgraph/pyqtgraph#371]
Hi,

the default behavior moves `numpy.NaN` to the minimum of the lookuptable. Can we add more control on how to handle missing data.

cheers!

**Comment by miili** [comment]
Fixed with #406

**Comment by vascotenner** [comment]
I found such behaviour also here:

```
small = np.zeros((3,3))
small[-1] = 1
small[1] = np.nan
md.img1a.setImage(small)
```
with ```md.img1a``` an ```ImageItem```. Will PR #406 also fix this?

**Comment by miili** [comment]
Yes, should do it. Darn why is this not merged yet?

**Comment by my-myth** [comment]
The problem still exist for images, where we can not have a tansperant pixels.
Any solutions ?

**Comment by BenBagherian** [comment]
any solution for transparent pixels? My data is NOT continuous all the time.

**Comment by ixjlyons** [comment]
Fixed by #406
