### ISSUE TITLE
ImageExporter.py", line 70, in export => TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by georgesk** [pyqtgraph/pyqtgraph#538]
Hello, I found a little bug which I fixed easily, about the construction of a np array.

This occurs with Python3, when the defaul numeric type may be float. I had to constrain two values to int type.

Here is a unified diff snippet:

------------------------------------
--- /usr/lib/python3/dist-packages/pyqtgraph/exporters/ImageExporter.py.orig	2017-08-25 18:05:45.174068717 +0200
+++ /usr/lib/python3/dist-packages/pyqtgraph/exporters/ImageExporter.py	2017-08-25 18:09:09.105402942 +0200
@@ -67,7 +67,7 @@
         w, h = self.params['width'], self.params['height']
         if w == 0 or h == 0:
             raise Exception("Cannot export image with size=0 (requested export size is %dx%d)" % (w,h))
-        bg = np.empty((self.params['width'], self.params['height'], 4), dtype=np.ubyte)
+        bg = np.empty((int(self.params['width']), int(self.params['height']), 4), dtype=np.ubyte)
         color = self.params['background']
         bg[:,:,0] = color.blue()
         bg[:,:,1] = color.green()

**Comment by jorepstein1** [comment]
This doesn't seem to be a Python 3 bug actually. I am on Python 2.

I ran into this same problem and found that my version of pyqtgraph was did not include recent changes to master that fixed this bug. It looks like pull #479 added changes to class SimpleParameter in  pyqtgraph.parametertree.parameterTypes.py that should fix this.

**Comment by jamesstidard** [comment]
The last released version (0.10.0) which is availible on pypi still have this issue. Is there a suggested stable git commit I can install from or is pointing at the head of master stable? Thanks.

**Comment by rkrupnek** [comment]
*Bump*

**Comment by eliavv** [comment]
Same problem here...
Python 3.5.3 + pyqtgraph 0.10.0

**Comment by chronologist89** [comment]
I use the following contruct to circumvent the problem:

`exporter.params.param('width').setValue(1920, blockSignal=exporter.widthChanged)`
`exporter.params.param('height').setValue(1080, blockSignal=exporter.heightChanged)`

This way I don't have to modify internal code. Beware, if you set the values to the default values (640, 480) the variables will not update their type to int!

**Comment by corbinhaugen** [comment]
I just adjusted line 70 in "ImageExporter.py" to read:
`bg = np.empty((int(self.params['width']), int(self.params['height']), 4), dtype=np.ubyte)`

That way the height and width are cast as intergers which can be interpreted as indexes.

**Comment by pteromys** [comment]
I think this is a duplicate of #464 and/or #454. The fix in #458 probably also deserves mention, in addition to 479 (noted above); both are already merged into the `develop` branch.

(I guess jamesstidard's question of when the next release is going to be remains open.)

**Comment by ixjlyons** [comment]
This should be fixed as of #458 and #479. Feel free to re-open if you're still experiencing this issue with the latest `develop` branch.

**Comment by Mathieu1972** [comment]
I just did this:  at line 67 change the program ImageExporter.py with this  
 w, h = int(self.params['width']), int(self.params['height'])
  if w == 0 or h == 0:
            raise Exception("Cannot export image with size=0 (requested export size is %dx%d)" % (w,h))
 #####To replace: bg = np.empty((self.params['width'], self.params['height'], 4), dtype=np.ubyte)
  bg = np.empty((w, h, 4), dtype=np.ubyte)
